services:
  app:
    build: .
    platform: linux/amd64
    container_name: omnij
    env_file:
      - /Users/spawd/.env_omnij
    volumes:
      - ./src/main/java/com/brandongcobb/omnij:/app/source
    command: java -jar app/Application.jar
